# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\hoctap\PROJECT1\KATodoList\ui\adminInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adminInterface(object):
    def setupUi(self, adminInterface):
        adminInterface.setObjectName("adminInterface")
        adminInterface.resize(1620, 920)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\hoctap\\PROJECT1\\KATodoList\\ui\\img/AppIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        adminInterface.setWindowIcon(icon)
        adminInterface.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btndeleteUser = QtWidgets.QPushButton(adminInterface)
        self.btndeleteUser.setGeometry(QtCore.QRect(1250, 800, 120, 40))
        self.btndeleteUser.setStyleSheet("background-color: rgb(210, 212, 255);\n"
"font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.btndeleteUser.setObjectName("btndeleteUser")
        self.btnsignOutAdmin = QtWidgets.QPushButton(adminInterface)
        self.btnsignOutAdmin.setGeometry(QtCore.QRect(1420, 20, 100, 40))
        self.btnsignOutAdmin.setStyleSheet("\n"
"background-color: rgb(210, 212, 255);\n"
"font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.btnsignOutAdmin.setObjectName("btnsignOutAdmin")
        self.listOfUser = QtWidgets.QTableWidget(adminInterface)
        self.listOfUser.setGeometry(QtCore.QRect(100, 200, 1420, 580))
        self.listOfUser.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.listOfUser.setObjectName("listOfUser")
        self.listOfUser.setColumnCount(2)
        self.listOfUser.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listOfUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listOfUser.setHorizontalHeaderItem(1, item)
        self.btnaddUser = QtWidgets.QPushButton(adminInterface)
        self.btnaddUser.setGeometry(QtCore.QRect(1100, 800, 120, 40))
        self.btnaddUser.setStyleSheet("background-color: rgb(210, 212, 255);\n"
"font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.btnaddUser.setObjectName("btnaddUser")
        self.btnsaveUser = QtWidgets.QPushButton(adminInterface)
        self.btnsaveUser.setGeometry(QtCore.QRect(1400, 800, 120, 40))
        self.btnsaveUser.setStyleSheet("background-color: rgb(210, 212, 255);\n"
"font: 63 9pt \"Yu Gothic UI Semibold\";")
        self.btnsaveUser.setObjectName("btnsaveUser")
        self.toDoList = QtWidgets.QLabel(adminInterface)
        self.toDoList.setGeometry(QtCore.QRect(670, 50, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.toDoList.setFont(font)
        self.toDoList.setObjectName("toDoList")

        self.retranslateUi(adminInterface)
        QtCore.QMetaObject.connectSlotsByName(adminInterface)

    def retranslateUi(self, adminInterface):
        _translate = QtCore.QCoreApplication.translate
        adminInterface.setWindowTitle(_translate("adminInterface", "KATotoList"))
        self.btndeleteUser.setText(_translate("adminInterface", "Delete User"))
        self.btnsignOutAdmin.setText(_translate("adminInterface", "Sign out"))
        item = self.listOfUser.horizontalHeaderItem(0)
        item.setText(_translate("adminInterface", "Username"))
        item = self.listOfUser.horizontalHeaderItem(1)
        item.setText(_translate("adminInterface", "Password"))
        self.btnaddUser.setText(_translate("adminInterface", "Add User"))
        self.btnsaveUser.setText(_translate("adminInterface", "Save all"))
        self.toDoList.setText(_translate("adminInterface", "<html><head/><body><p><span style=\" font-size:36pt;\">Todo list</span></p></body></html>"))
