# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\hoctap\PROJECT1\KATodoList\ui\signIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signIn(object):
    def setupUi(self, signIn):
        signIn.setObjectName("signIn")
        signIn.resize(1620, 920)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\hoctap\\PROJECT1\\KATodoList\\ui\\../img/AppIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signIn.setWindowIcon(icon)
        signIn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toDoList = QtWidgets.QLabel(signIn)
        self.toDoList.setGeometry(QtCore.QRect(670, 50, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.toDoList.setFont(font)
        self.toDoList.setObjectName("toDoList")
        self.signInText = QtWidgets.QLabel(signIn)
        self.signInText.setGeometry(QtCore.QRect(740, 200, 200, 80))
        self.signInText.setObjectName("signInText")
        self.userNameText = QtWidgets.QLabel(signIn)
        self.userNameText.setGeometry(QtCore.QRect(500, 350, 150, 40))
        self.userNameText.setObjectName("userNameText")
        self.passwordText = QtWidgets.QLabel(signIn)
        self.passwordText.setGeometry(QtCore.QRect(500, 420, 150, 40))
        self.passwordText.setObjectName("passwordText")
        self.useNameFill = QtWidgets.QLineEdit(signIn)
        self.useNameFill.setGeometry(QtCore.QRect(700, 350, 400, 40))
        self.useNameFill.setStyleSheet("border-color: rgb(0, 85, 127);")
        self.useNameFill.setObjectName("useNameFill")
        self.passwordFillIn = QtWidgets.QLineEdit(signIn)
        self.passwordFillIn.setGeometry(QtCore.QRect(700, 420, 400, 40))
        self.passwordFillIn.setObjectName("passwordFillIn")
        self.btnSignIn_In = QtWidgets.QPushButton(signIn)
        self.btnSignIn_In.setGeometry(QtCore.QRect(500, 520, 250, 50))
        self.btnSignIn_In.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"font: 9pt \"Segoe UI Historic\";\n"
"")
        self.btnSignIn_In.setObjectName("btnSignIn_In")
        self.btnSignUp_In = QtWidgets.QPushButton(signIn)
        self.btnSignUp_In.setGeometry(QtCore.QRect(850, 520, 250, 50))
        self.btnSignUp_In.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.btnSignUp_In.setObjectName("btnSignUp_In")

        self.retranslateUi(signIn)
        QtCore.QMetaObject.connectSlotsByName(signIn)

    def retranslateUi(self, signIn):
        _translate = QtCore.QCoreApplication.translate
        signIn.setWindowTitle(_translate("signIn", "KATodoList"))
        self.toDoList.setText(_translate("signIn", "<html><head/><body><p><span style=\" font-size:36pt;\">Todo list</span></p></body></html>"))
        self.signInText.setText(_translate("signIn", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#00557f;\">Sign in</span></p></body></html>"))
        self.userNameText.setText(_translate("signIn", "<html><head/><body><p><span style=\" font-size:12pt;\">Username</span></p></body></html>"))
        self.passwordText.setText(_translate("signIn", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.btnSignIn_In.setText(_translate("signIn", "Sign in"))
        self.btnSignUp_In.setText(_translate("signIn", "Sign up"))
