# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\hoctap\PROJECT1\KATodoList\ui\signUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signUp(object):
    def setupUi(self, signUp):
        signUp.setObjectName("signUp")
        signUp.resize(1620, 920)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\hoctap\\PROJECT1\\KATodoList\\ui\\img/AppIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signUp.setWindowIcon(icon)
        signUp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwordFillUp = QtWidgets.QLineEdit(signUp)
        self.passwordFillUp.setGeometry(QtCore.QRect(700, 420, 400, 40))
        self.passwordFillUp.setObjectName("passwordFillUp")
        self.useNameFill = QtWidgets.QLineEdit(signUp)
        self.useNameFill.setGeometry(QtCore.QRect(700, 350, 400, 40))
        self.useNameFill.setStyleSheet("border-color: rgb(0, 85, 127);")
        self.useNameFill.setObjectName("useNameFill")
        self.signUpText = QtWidgets.QLabel(signUp)
        self.signUpText.setGeometry(QtCore.QRect(740, 200, 200, 80))
        self.signUpText.setObjectName("signUpText")
        self.toDoList = QtWidgets.QLabel(signUp)
        self.toDoList.setGeometry(QtCore.QRect(670, 50, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.toDoList.setFont(font)
        self.toDoList.setObjectName("toDoList")
        self.passwordText = QtWidgets.QLabel(signUp)
        self.passwordText.setGeometry(QtCore.QRect(500, 420, 150, 40))
        self.passwordText.setObjectName("passwordText")
        self.userNameText = QtWidgets.QLabel(signUp)
        self.userNameText.setGeometry(QtCore.QRect(500, 350, 150, 40))
        self.userNameText.setObjectName("userNameText")
        self.verifyPassword = QtWidgets.QLineEdit(signUp)
        self.verifyPassword.setGeometry(QtCore.QRect(700, 490, 400, 40))
        self.verifyPassword.setObjectName("verifyPassword")
        self.passwordText_2 = QtWidgets.QLabel(signUp)
        self.passwordText_2.setGeometry(QtCore.QRect(500, 490, 200, 40))
        self.passwordText_2.setObjectName("passwordText_2")
        self.btnSignUp_Up = QtWidgets.QPushButton(signUp)
        self.btnSignUp_Up.setGeometry(QtCore.QRect(500, 590, 250, 50))
        self.btnSignUp_Up.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"font: 9pt \"Segoe UI Historic\";\n"
"")
        self.btnSignUp_Up.setObjectName("btnSignUp_Up")
        self.btnSignIn_Up = QtWidgets.QPushButton(signUp)
        self.btnSignIn_Up.setGeometry(QtCore.QRect(850, 590, 250, 50))
        self.btnSignIn_Up.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.btnSignIn_Up.setObjectName("btnSignIn_Up")

        self.retranslateUi(signUp)
        QtCore.QMetaObject.connectSlotsByName(signUp)

    def retranslateUi(self, signUp):
        _translate = QtCore.QCoreApplication.translate
        signUp.setWindowTitle(_translate("signUp", "KATodoList"))
        self.signUpText.setText(_translate("signUp", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#00557f;\">Sign up</span></p></body></html>"))
        self.toDoList.setText(_translate("signUp", "<html><head/><body><p><span style=\" font-size:36pt;\">Todo list</span></p></body></html>"))
        self.passwordText.setText(_translate("signUp", "<html><head/><body><p><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
        self.userNameText.setText(_translate("signUp", "<html><head/><body><p><span style=\" font-size:12pt;\">Username</span></p></body></html>"))
        self.passwordText_2.setText(_translate("signUp", "<html><head/><body><p><span style=\" font-size:12pt;\">Verify password</span></p></body></html>"))
        self.btnSignUp_Up.setText(_translate("signUp", "Sign up"))
        self.btnSignIn_Up.setText(_translate("signUp", "Sign in"))
